// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: workload.proto

package workloadv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// WorkloadType represents the type of Kubernetes workload
type WorkloadType int32

const (
	WorkloadType_WORKLOAD_TYPE_UNSPECIFIED WorkloadType = 0
	WorkloadType_WORKLOAD_TYPE_DEPLOYMENT  WorkloadType = 1
	WorkloadType_WORKLOAD_TYPE_STATEFULSET WorkloadType = 2
	WorkloadType_WORKLOAD_TYPE_DAEMONSET   WorkloadType = 3
)

// Enum value maps for WorkloadType.
var (
	WorkloadType_name = map[int32]string{
		0: "WORKLOAD_TYPE_UNSPECIFIED",
		1: "WORKLOAD_TYPE_DEPLOYMENT",
		2: "WORKLOAD_TYPE_STATEFULSET",
		3: "WORKLOAD_TYPE_DAEMONSET",
	}
	WorkloadType_value = map[string]int32{
		"WORKLOAD_TYPE_UNSPECIFIED": 0,
		"WORKLOAD_TYPE_DEPLOYMENT":  1,
		"WORKLOAD_TYPE_STATEFULSET": 2,
		"WORKLOAD_TYPE_DAEMONSET":   3,
	}
)

func (x WorkloadType) Enum() *WorkloadType {
	p := new(WorkloadType)
	*p = x
	return p
}

func (x WorkloadType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (WorkloadType) Descriptor() protoreflect.EnumDescriptor {
	return file_workload_proto_enumTypes[0].Descriptor()
}

func (WorkloadType) Type() protoreflect.EnumType {
	return &file_workload_proto_enumTypes[0]
}

func (x WorkloadType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use WorkloadType.Descriptor instead.
func (WorkloadType) EnumDescriptor() ([]byte, []int) {
	return file_workload_proto_rawDescGZIP(), []int{0}
}

// RestartRequest contains the workload type and name to restart
type RestartRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          WorkloadType           `protobuf:"varint,1,opt,name=type,proto3,enum=workload.v1.WorkloadType" json:"type,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Namespace     string                 `protobuf:"bytes,3,opt,name=namespace,proto3" json:"namespace,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RestartRequest) Reset() {
	*x = RestartRequest{}
	mi := &file_workload_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RestartRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RestartRequest) ProtoMessage() {}

func (x *RestartRequest) ProtoReflect() protoreflect.Message {
	mi := &file_workload_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RestartRequest.ProtoReflect.Descriptor instead.
func (*RestartRequest) Descriptor() ([]byte, []int) {
	return file_workload_proto_rawDescGZIP(), []int{0}
}

func (x *RestartRequest) GetType() WorkloadType {
	if x != nil {
		return x.Type
	}
	return WorkloadType_WORKLOAD_TYPE_UNSPECIFIED
}

func (x *RestartRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *RestartRequest) GetNamespace() string {
	if x != nil {
		return x.Namespace
	}
	return ""
}

// RestartResponse contains the result of the restart operation
type RestartResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RestartResponse) Reset() {
	*x = RestartResponse{}
	mi := &file_workload_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RestartResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RestartResponse) ProtoMessage() {}

func (x *RestartResponse) ProtoReflect() protoreflect.Message {
	mi := &file_workload_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RestartResponse.ProtoReflect.Descriptor instead.
func (*RestartResponse) Descriptor() ([]byte, []int) {
	return file_workload_proto_rawDescGZIP(), []int{1}
}

func (x *RestartResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *RestartResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

// ServiceInfo contains information about the configured restart service
type ServiceInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Enabled       bool                   `protobuf:"varint,1,opt,name=enabled,proto3" json:"enabled,omitempty"`
	Type          WorkloadType           `protobuf:"varint,2,opt,name=type,proto3,enum=workload.v1.WorkloadType" json:"type,omitempty"`
	Name          string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ServiceInfo) Reset() {
	*x = ServiceInfo{}
	mi := &file_workload_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServiceInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServiceInfo) ProtoMessage() {}

func (x *ServiceInfo) ProtoReflect() protoreflect.Message {
	mi := &file_workload_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServiceInfo.ProtoReflect.Descriptor instead.
func (*ServiceInfo) Descriptor() ([]byte, []int) {
	return file_workload_proto_rawDescGZIP(), []int{2}
}

func (x *ServiceInfo) GetEnabled() bool {
	if x != nil {
		return x.Enabled
	}
	return false
}

func (x *ServiceInfo) GetType() WorkloadType {
	if x != nil {
		return x.Type
	}
	return WorkloadType_WORKLOAD_TYPE_UNSPECIFIED
}

func (x *ServiceInfo) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

// InfoRequest is an empty request for getting service info
type InfoRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InfoRequest) Reset() {
	*x = InfoRequest{}
	mi := &file_workload_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InfoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InfoRequest) ProtoMessage() {}

func (x *InfoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_workload_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InfoRequest.ProtoReflect.Descriptor instead.
func (*InfoRequest) Descriptor() ([]byte, []int) {
	return file_workload_proto_rawDescGZIP(), []int{3}
}

// SimpleRestartRequest is an empty request that uses configured values
type SimpleRestartRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SimpleRestartRequest) Reset() {
	*x = SimpleRestartRequest{}
	mi := &file_workload_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SimpleRestartRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SimpleRestartRequest) ProtoMessage() {}

func (x *SimpleRestartRequest) ProtoReflect() protoreflect.Message {
	mi := &file_workload_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SimpleRestartRequest.ProtoReflect.Descriptor instead.
func (*SimpleRestartRequest) Descriptor() ([]byte, []int) {
	return file_workload_proto_rawDescGZIP(), []int{4}
}

var File_workload_proto protoreflect.FileDescriptor

const file_workload_proto_rawDesc = "" +
	"\n" +
	"\x0eworkload.proto\x12\vworkload.v1\"q\n" +
	"\x0eRestartRequest\x12-\n" +
	"\x04type\x18\x01 \x01(\x0e2\x19.workload.v1.WorkloadTypeR\x04type\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x1c\n" +
	"\tnamespace\x18\x03 \x01(\tR\tnamespace\"E\n" +
	"\x0fRestartResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"j\n" +
	"\vServiceInfo\x12\x18\n" +
	"\aenabled\x18\x01 \x01(\bR\aenabled\x12-\n" +
	"\x04type\x18\x02 \x01(\x0e2\x19.workload.v1.WorkloadTypeR\x04type\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\"\r\n" +
	"\vInfoRequest\"\x16\n" +
	"\x14SimpleRestartRequest*\x87\x01\n" +
	"\fWorkloadType\x12\x1d\n" +
	"\x19WORKLOAD_TYPE_UNSPECIFIED\x10\x00\x12\x1c\n" +
	"\x18WORKLOAD_TYPE_DEPLOYMENT\x10\x01\x12\x1d\n" +
	"\x19WORKLOAD_TYPE_STATEFULSET\x10\x02\x12\x1b\n" +
	"\x17WORKLOAD_TYPE_DAEMONSET\x10\x032\xe0\x01\n" +
	"\bWorkload\x12L\n" +
	"\x0fRestartWorkload\x12\x1b.workload.v1.RestartRequest\x1a\x1c.workload.v1.RestartResponse\x12:\n" +
	"\x04Info\x12\x18.workload.v1.InfoRequest\x1a\x18.workload.v1.ServiceInfo\x12J\n" +
	"\aRestart\x12!.workload.v1.SimpleRestartRequest\x1a\x1c.workload.v1.RestartResponseBKZIgithub.com/dkrizic/feature/service/service/workload/workloadv1;workloadv1b\x06proto3"

var (
	file_workload_proto_rawDescOnce sync.Once
	file_workload_proto_rawDescData []byte
)

func file_workload_proto_rawDescGZIP() []byte {
	file_workload_proto_rawDescOnce.Do(func() {
		file_workload_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_workload_proto_rawDesc), len(file_workload_proto_rawDesc)))
	})
	return file_workload_proto_rawDescData
}

var file_workload_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_workload_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_workload_proto_goTypes = []any{
	(WorkloadType)(0),            // 0: workload.v1.WorkloadType
	(*RestartRequest)(nil),       // 1: workload.v1.RestartRequest
	(*RestartResponse)(nil),      // 2: workload.v1.RestartResponse
	(*ServiceInfo)(nil),          // 3: workload.v1.ServiceInfo
	(*InfoRequest)(nil),          // 4: workload.v1.InfoRequest
	(*SimpleRestartRequest)(nil), // 5: workload.v1.SimpleRestartRequest
}
var file_workload_proto_depIdxs = []int32{
	0, // 0: workload.v1.RestartRequest.type:type_name -> workload.v1.WorkloadType
	0, // 1: workload.v1.ServiceInfo.type:type_name -> workload.v1.WorkloadType
	1, // 2: workload.v1.Workload.RestartWorkload:input_type -> workload.v1.RestartRequest
	4, // 3: workload.v1.Workload.Info:input_type -> workload.v1.InfoRequest
	5, // 4: workload.v1.Workload.Restart:input_type -> workload.v1.SimpleRestartRequest
	2, // 5: workload.v1.Workload.RestartWorkload:output_type -> workload.v1.RestartResponse
	3, // 6: workload.v1.Workload.Info:output_type -> workload.v1.ServiceInfo
	2, // 7: workload.v1.Workload.Restart:output_type -> workload.v1.RestartResponse
	5, // [5:8] is the sub-list for method output_type
	2, // [2:5] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_workload_proto_init() }
func file_workload_proto_init() {
	if File_workload_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_workload_proto_rawDesc), len(file_workload_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_workload_proto_goTypes,
		DependencyIndexes: file_workload_proto_depIdxs,
		EnumInfos:         file_workload_proto_enumTypes,
		MessageInfos:      file_workload_proto_msgTypes,
	}.Build()
	File_workload_proto = out.File
	file_workload_proto_goTypes = nil
	file_workload_proto_depIdxs = nil
}
