// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: feature.proto

package featurev1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Key struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Application   string                 `protobuf:"bytes,2,opt,name=application,proto3" json:"application,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Key) Reset() {
	*x = Key{}
	mi := &file_feature_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Key) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Key) ProtoMessage() {}

func (x *Key) ProtoReflect() protoreflect.Message {
	mi := &file_feature_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Key.ProtoReflect.Descriptor instead.
func (*Key) Descriptor() ([]byte, []int) {
	return file_feature_proto_rawDescGZIP(), []int{0}
}

func (x *Key) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Key) GetApplication() string {
	if x != nil {
		return x.Application
	}
	return ""
}

type Value struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Value) Reset() {
	*x = Value{}
	mi := &file_feature_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Value) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Value) ProtoMessage() {}

func (x *Value) ProtoReflect() protoreflect.Message {
	mi := &file_feature_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Value.ProtoReflect.Descriptor instead.
func (*Value) Descriptor() ([]byte, []int) {
	return file_feature_proto_rawDescGZIP(), []int{1}
}

func (x *Value) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type KeyValue struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           string                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Value         string                 `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	Editable      bool                   `protobuf:"varint,3,opt,name=editable,proto3" json:"editable,omitempty"`
	Application   string                 `protobuf:"bytes,4,opt,name=application,proto3" json:"application,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *KeyValue) Reset() {
	*x = KeyValue{}
	mi := &file_feature_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *KeyValue) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KeyValue) ProtoMessage() {}

func (x *KeyValue) ProtoReflect() protoreflect.Message {
	mi := &file_feature_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KeyValue.ProtoReflect.Descriptor instead.
func (*KeyValue) Descriptor() ([]byte, []int) {
	return file_feature_proto_rawDescGZIP(), []int{2}
}

func (x *KeyValue) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *KeyValue) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

func (x *KeyValue) GetEditable() bool {
	if x != nil {
		return x.Editable
	}
	return false
}

func (x *KeyValue) GetApplication() string {
	if x != nil {
		return x.Application
	}
	return ""
}

type ApplicationsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ApplicationsRequest) Reset() {
	*x = ApplicationsRequest{}
	mi := &file_feature_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ApplicationsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ApplicationsRequest) ProtoMessage() {}

func (x *ApplicationsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_feature_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ApplicationsRequest.ProtoReflect.Descriptor instead.
func (*ApplicationsRequest) Descriptor() ([]byte, []int) {
	return file_feature_proto_rawDescGZIP(), []int{3}
}

type Application struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Namespace     string                 `protobuf:"bytes,2,opt,name=namespace,proto3" json:"namespace,omitempty"`
	StorageType   string                 `protobuf:"bytes,3,opt,name=storage_type,json=storageType,proto3" json:"storage_type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Application) Reset() {
	*x = Application{}
	mi := &file_feature_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Application) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Application) ProtoMessage() {}

func (x *Application) ProtoReflect() protoreflect.Message {
	mi := &file_feature_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Application.ProtoReflect.Descriptor instead.
func (*Application) Descriptor() ([]byte, []int) {
	return file_feature_proto_rawDescGZIP(), []int{4}
}

func (x *Application) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Application) GetNamespace() string {
	if x != nil {
		return x.Namespace
	}
	return ""
}

func (x *Application) GetStorageType() string {
	if x != nil {
		return x.StorageType
	}
	return ""
}

var File_feature_proto protoreflect.FileDescriptor

const file_feature_proto_rawDesc = "" +
	"\n" +
	"\rfeature.proto\x12\n" +
	"feature.v1\x1a\x1bgoogle/protobuf/empty.proto\";\n" +
	"\x03Key\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12 \n" +
	"\vapplication\x18\x02 \x01(\tR\vapplication\"\x1b\n" +
	"\x05Value\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\"p\n" +
	"\bKeyValue\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value\x12\x1a\n" +
	"\beditable\x18\x03 \x01(\bR\beditable\x12 \n" +
	"\vapplication\x18\x04 \x01(\tR\vapplication\"\x15\n" +
	"\x13ApplicationsRequest\"b\n" +
	"\vApplication\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x1c\n" +
	"\tnamespace\x18\x02 \x01(\tR\tnamespace\x12!\n" +
	"\fstorage_type\x18\x03 \x01(\tR\vstorageType2\xdd\x02\n" +
	"\aFeature\x128\n" +
	"\x06GetAll\x12\x16.google.protobuf.Empty\x1a\x14.feature.v1.KeyValue0\x01\x126\n" +
	"\x06PreSet\x12\x14.feature.v1.KeyValue\x1a\x16.google.protobuf.Empty\x123\n" +
	"\x03Set\x12\x14.feature.v1.KeyValue\x1a\x16.google.protobuf.Empty\x12)\n" +
	"\x03Get\x12\x0f.feature.v1.Key\x1a\x11.feature.v1.Value\x121\n" +
	"\x06Delete\x12\x0f.feature.v1.Key\x1a\x16.google.protobuf.Empty\x12M\n" +
	"\x0fGetApplications\x12\x1f.feature.v1.ApplicationsRequest\x1a\x17.feature.v1.Application0\x01BHZFgithub.com/dkrizic/feature/service/service/feature/featurev1;featurev1b\x06proto3"

var (
	file_feature_proto_rawDescOnce sync.Once
	file_feature_proto_rawDescData []byte
)

func file_feature_proto_rawDescGZIP() []byte {
	file_feature_proto_rawDescOnce.Do(func() {
		file_feature_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_feature_proto_rawDesc), len(file_feature_proto_rawDesc)))
	})
	return file_feature_proto_rawDescData
}

var file_feature_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_feature_proto_goTypes = []any{
	(*Key)(nil),                 // 0: feature.v1.Key
	(*Value)(nil),               // 1: feature.v1.Value
	(*KeyValue)(nil),            // 2: feature.v1.KeyValue
	(*ApplicationsRequest)(nil), // 3: feature.v1.ApplicationsRequest
	(*Application)(nil),         // 4: feature.v1.Application
	(*emptypb.Empty)(nil),       // 5: google.protobuf.Empty
}
var file_feature_proto_depIdxs = []int32{
	5, // 0: feature.v1.Feature.GetAll:input_type -> google.protobuf.Empty
	2, // 1: feature.v1.Feature.PreSet:input_type -> feature.v1.KeyValue
	2, // 2: feature.v1.Feature.Set:input_type -> feature.v1.KeyValue
	0, // 3: feature.v1.Feature.Get:input_type -> feature.v1.Key
	0, // 4: feature.v1.Feature.Delete:input_type -> feature.v1.Key
	3, // 5: feature.v1.Feature.GetApplications:input_type -> feature.v1.ApplicationsRequest
	2, // 6: feature.v1.Feature.GetAll:output_type -> feature.v1.KeyValue
	5, // 7: feature.v1.Feature.PreSet:output_type -> google.protobuf.Empty
	5, // 8: feature.v1.Feature.Set:output_type -> google.protobuf.Empty
	1, // 9: feature.v1.Feature.Get:output_type -> feature.v1.Value
	5, // 10: feature.v1.Feature.Delete:output_type -> google.protobuf.Empty
	4, // 11: feature.v1.Feature.GetApplications:output_type -> feature.v1.Application
	6, // [6:12] is the sub-list for method output_type
	0, // [0:6] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_feature_proto_init() }
func file_feature_proto_init() {
	if File_feature_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_feature_proto_rawDesc), len(file_feature_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_feature_proto_goTypes,
		DependencyIndexes: file_feature_proto_depIdxs,
		MessageInfos:      file_feature_proto_msgTypes,
	}.Build()
	File_feature_proto = out.File
	file_feature_proto_goTypes = nil
	file_feature_proto_depIdxs = nil
}
