// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package workloadv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion7

// WorkloadClient is the client API for Workload service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type WorkloadClient interface {
	RestartWorkload(ctx context.Context, in *RestartRequest, opts ...grpc.CallOption) (*RestartResponse, error)
}

type workloadClient struct {
	cc grpc.ClientConnInterface
}

func NewWorkloadClient(cc grpc.ClientConnInterface) WorkloadClient {
	return &workloadClient{cc}
}

func (c *workloadClient) RestartWorkload(ctx context.Context, in *RestartRequest, opts ...grpc.CallOption) (*RestartResponse, error) {
	out := new(RestartResponse)
	err := c.cc.Invoke(ctx, "/workload.v1.Workload/RestartWorkload", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// WorkloadServer is the server API for Workload service.
// All implementations must embed UnimplementedWorkloadServer
// for forward compatibility
type WorkloadServer interface {
	RestartWorkload(context.Context, *RestartRequest) (*RestartResponse, error)
	mustEmbedUnimplementedWorkloadServer()
}

// UnimplementedWorkloadServer must be embedded to have forward compatible implementations.
type UnimplementedWorkloadServer struct {
}

func (UnimplementedWorkloadServer) RestartWorkload(context.Context, *RestartRequest) (*RestartResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RestartWorkload not implemented")
}
func (UnimplementedWorkloadServer) mustEmbedUnimplementedWorkloadServer() {}

// UnsafeWorkloadServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to WorkloadServer will
// result in compilation errors.
type UnsafeWorkloadServer interface {
	mustEmbedUnimplementedWorkloadServer()
}

func RegisterWorkloadServer(s *grpc.Server, srv WorkloadServer) {
	s.RegisterService(&_Workload_serviceDesc, srv)
}

func _Workload_RestartWorkload_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RestartRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WorkloadServer).RestartWorkload(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/workload.v1.Workload/RestartWorkload",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WorkloadServer).RestartWorkload(ctx, req.(*RestartRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Workload_serviceDesc = grpc.ServiceDesc{
	ServiceName: "workload.v1.Workload",
	HandlerType: (*WorkloadServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "RestartWorkload",
			Handler:    _Workload_RestartWorkload_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "workload.proto",
}
