// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.0
// - protoc             v5.28.3
// source: workload.proto

package workloadv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Workload_RestartWorkload_FullMethodName = "/workload.v1.Workload/RestartWorkload"
	Workload_Info_FullMethodName            = "/workload.v1.Workload/Info"
	Workload_Restart_FullMethodName         = "/workload.v1.Workload/Restart"
)

// WorkloadClient is the client API for Workload service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type WorkloadClient interface {
	RestartWorkload(ctx context.Context, in *RestartRequest, opts ...grpc.CallOption) (*RestartResponse, error)
	Info(ctx context.Context, in *InfoRequest, opts ...grpc.CallOption) (*ServiceInfo, error)
	Restart(ctx context.Context, in *SimpleRestartRequest, opts ...grpc.CallOption) (*RestartResponse, error)
}

type workloadClient struct {
	cc grpc.ClientConnInterface
}

func NewWorkloadClient(cc grpc.ClientConnInterface) WorkloadClient {
	return &workloadClient{cc}
}

func (c *workloadClient) RestartWorkload(ctx context.Context, in *RestartRequest, opts ...grpc.CallOption) (*RestartResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RestartResponse)
	err := c.cc.Invoke(ctx, Workload_RestartWorkload_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *workloadClient) Info(ctx context.Context, in *InfoRequest, opts ...grpc.CallOption) (*ServiceInfo, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ServiceInfo)
	err := c.cc.Invoke(ctx, Workload_Info_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *workloadClient) Restart(ctx context.Context, in *SimpleRestartRequest, opts ...grpc.CallOption) (*RestartResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RestartResponse)
	err := c.cc.Invoke(ctx, Workload_Restart_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// WorkloadServer is the server API for Workload service.
// All implementations must embed UnimplementedWorkloadServer
// for forward compatibility.
type WorkloadServer interface {
	RestartWorkload(context.Context, *RestartRequest) (*RestartResponse, error)
	Info(context.Context, *InfoRequest) (*ServiceInfo, error)
	Restart(context.Context, *SimpleRestartRequest) (*RestartResponse, error)
	mustEmbedUnimplementedWorkloadServer()
}

// UnimplementedWorkloadServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedWorkloadServer struct{}

func (UnimplementedWorkloadServer) RestartWorkload(context.Context, *RestartRequest) (*RestartResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method RestartWorkload not implemented")
}
func (UnimplementedWorkloadServer) Info(context.Context, *InfoRequest) (*ServiceInfo, error) {
	return nil, status.Error(codes.Unimplemented, "method Info not implemented")
}
func (UnimplementedWorkloadServer) Restart(context.Context, *SimpleRestartRequest) (*RestartResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Restart not implemented")
}
func (UnimplementedWorkloadServer) mustEmbedUnimplementedWorkloadServer() {}
func (UnimplementedWorkloadServer) testEmbeddedByValue()                  {}

// UnsafeWorkloadServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to WorkloadServer will
// result in compilation errors.
type UnsafeWorkloadServer interface {
	mustEmbedUnimplementedWorkloadServer()
}

func RegisterWorkloadServer(s grpc.ServiceRegistrar, srv WorkloadServer) {
	// If the following call panics, it indicates UnimplementedWorkloadServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Workload_ServiceDesc, srv)
}

func _Workload_RestartWorkload_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RestartRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WorkloadServer).RestartWorkload(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Workload_RestartWorkload_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WorkloadServer).RestartWorkload(ctx, req.(*RestartRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Workload_Info_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(InfoRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WorkloadServer).Info(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Workload_Info_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WorkloadServer).Info(ctx, req.(*InfoRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Workload_Restart_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SimpleRestartRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WorkloadServer).Restart(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Workload_Restart_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WorkloadServer).Restart(ctx, req.(*SimpleRestartRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Workload_ServiceDesc is the grpc.ServiceDesc for Workload service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Workload_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "workload.v1.Workload",
	HandlerType: (*WorkloadServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "RestartWorkload",
			Handler:    _Workload_RestartWorkload_Handler,
		},
		{
			MethodName: "Info",
			Handler:    _Workload_Info_Handler,
		},
		{
			MethodName: "Restart",
			Handler:    _Workload_Restart_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "workload.proto",
}
