package constant

const (
	LogFormat                  = "log-format"
	LogFormatJSON              = "json"
	LogFormatText              = "text"
	LogLevel                   = "log-level"
	LogLevelDebug              = "debug"
	LogLevelInfo               = "info"
	LogLevelWarn               = "warn"
	LogLevelError              = "error"
	Port                       = "port"
	OpenTelemetryEnabled       = "opentelemetry-enabled"
	OpenTelemetryEndpoint      = "opentelemetry-endpoint"
	StorageType                = "storage-type"
	ConfigMapName              = "configmap-name"
	StorageTypeInMemory        = "inmemory"
	StorageTypeConfigMap       = "configmap"
	PreSet                     = "preset"
	NotificationEnabled        = "notification-enabled"
	NotificationType           = "notification-type"
	NotificationTypeLog        = "log"
	NotificationTypeRedisTopic = "redis_topic"
	RedisEndpoint              = "redis-endpoint"
	RedisNotificationTopic     = "redis-notification-topic"
	RestartEnabled             = "restart-enabled"
	RestartType                = "restart-type"
	RestartName                = "restart-name"
	Editable                   = "editable"
)
