proto:
	protoc -I meta --go_opt=paths=source_relative --go-grpc_opt=paths=source_relative --go_out=../service/service/meta/metav1 --go-grpc_out=../service/service/meta/metav1 meta/meta.proto
#	protoc -I api/ingester/proto --go_opt=paths=source_relative --go-grpc_opt=paths=source_relative --go_out=api/ingester/gen --go-grpc_out=api/ingester/gen api/ingester/proto/ingester.proto
